[LegacyColorValue = true]; 

{
***** Study name: 'EarlyBird III Demo'
}

{ ***** INPUTs Section *****}
Inputs: TIMEOFFSET(0);
{ ***** VARs Section ***** }
Variables: LENTRIES(0), SENTRIES(0), SPECTREND(0), SPECLENTRIES(0);
Variables: SPECSENTRIES(0), SCENTRIES(0), LCENTRIES(0), STENTRIESB(0);
Variables: LTENTRIESB(0), LTRENDREV(0), STRENDREV(0), LTRENTRIES(0);
Variables: STRENTRIES(0), WEAKCONTRA(0), TODAYTRADES(0), SRETRACE(0);
Variables: LRETRACE(0), RETRACESELL(0), RETRACEBUY(0), VALUE11(0);
Variables: VALUE2(0), VALUE3(0), VALUE4(0), VALUE5(0);

{ ***** CODE Section ***** }

IF CURRENTBAR = 1 THEN VALUE11 = CLOSE DATA (2) ;
IF DATE > DATE[1] THEN VALUE11 = CLOSE DATA (2) ;
IF DATE > DATE[1] OR TIME > 1500+TIMEOFFSET THEN 
   BEGIN
      LENTRIES = 0 ;
      SENTRIES = 0 ;
      SPECTREND = 0 ;
      SPECLENTRIES = 0 ;
      SPECSENTRIES = 0 ;
      SCENTRIES = 0 ;
      LCENTRIES = 0 ;
      STENTRIESB = 0 ;
      LTENTRIESB = 0 ;
      LTRENDREV = 0 ;
      STRENDREV = 0 ;
      LTRENTRIES = 0 ;
      STRENTRIES = 0 ;
      WEAKCONTRA = 0 ;
      TODAYTRADES = 0 ;
      SRETRACE = 0 ;
      LRETRACE = 0 ;
      RETRACESELL = 0 ;
      RETRACEBUY = 0 ;
   END ;
   
IF TIME = SESS1ENDTIME THEN 
   BEGIN
      VALUE2 = 0 ;
      VALUE3 = 0 ;
      VALUE4 = 0 ;
      VALUE5 = 0 ;
   END ;
   
IF TIME = 900+TIMEOFFSET THEN 
   BEGIN
      VALUE2 = HIGH DATA (2) ;
      VALUE3 = LOW DATA (2) ;
   END ;
   
IF TIME = 930+TIMEOFFSET THEN 
   BEGIN
      VALUE4 = HIGH DATA (2) ;
      VALUE5 = LOW DATA (2) ;
   END ;
   
IF TIME >= 930+TIMEOFFSET AND TIME < 1500+TIMEOFFSET THEN 
   BEGIN
      IF TIME >= 1000+TIMEOFFSET AND VALUE2 > 0 AND LOW DATA (2) >= LOW[1] DATA (2) THEN 
      BEGIN
         SRETRACE = 1 ;
         RETRACESELL = LOW DATA (2) ;
      END ;
      
      IF TIME >= 1000+TIMEOFFSET AND VALUE2 > 0 AND HIGH DATA (2) <= HIGH[1] DATA (2) THEN 
      BEGIN
         LRETRACE = 1 ;
         RETRACEBUY = HIGH DATA (2) ;
      END ;
      
      IF (VALUE2-VALUE11) >= 0.010000*VALUE11 THEN 
      BEGIN
         IF LENTRIES < 1 AND SENTRIES < 1 THEN Buy ("L1") NEXT BAR MAXLIST (VALUE2, VALUE4)+0.050000 STOP ;
         IF LENTRIES < 1 AND SENTRIES < 1 AND IDLow > VALUE11 AND LRETRACE = 1 THEN Buy ("L2") NEXT BAR RETRACEBUY+0.050000 STOP ;
      END ;
      
      IF (VALUE11-VALUE3) >= 0.010000*VALUE11 THEN 
      BEGIN
         IF SENTRIES < 1 AND LENTRIES < 1 THEN Sell Short ("S1") NEXT BAR MINLIST (VALUE3, VALUE5)-0.050000 STOP ;
         IF SENTRIES < 1 AND LENTRIES < 1 AND IDHigh < VALUE11 AND SRETRACE = 1 THEN Sell Short ("S2") NEXT BAR RETRACESELL-0.050000 STOP ;
      END ;
      
END ;
   
   Sell ("L1Exit2") NEXT BAR ENTRY ("L2") AT LOW DATA (2)-0.700000 STOP ;
   Buy to Cover ("S1Exit2") NEXT BAR ENTRY ("S2") AT HIGH DATA (2)+0.700000 STOP ;
   IF MARKETPOSITION > 0 THEN 
   BEGIN
      LENTRIES = 1 ;
      Sell ("LX1") NEXT BAR ENTRY ("L1") ENTRYPRICE+0.015000*VALUE11 LIMIT ;
      Sell ("LX12") NEXT BAR ENTRY ("L2") ENTRYPRICE+0.020000*VALUE11 LIMIT ;
      Sell ("LX2") NEXT BAR ENTRY ("L1") ENTRYPRICE-(0.009000*VALUE11) STOP ;
      Sell ("LX22") NEXT BAR ENTRY ("L2") ENTRYPRICE-(0.009000*VALUE11) STOP ;
   END ;
   
   IF MARKETPOSITION < 0 THEN 
   BEGIN
      SENTRIES = 1 ;
      Buy to Cover ("SX1") NEXT BAR ENTRY ("S1") ENTRYPRICE-0.015000*VALUE11 LIMIT ;
      Buy to Cover ("SX12") NEXT BAR ENTRY ("S2") ENTRYPRICE-0.020000*VALUE11 LIMIT ;
      Buy to Cover ("SX2") NEXT BAR ENTRY ("S1") ENTRYPRICE+(0.009000*VALUE11) STOP ;
      Buy to Cover ("SX22") NEXT BAR ENTRY ("S2") ENTRYPRICE+(0.009000*VALUE11) STOP ;
   END ;
   
   IF TIME >= 930+TIMEOFFSET AND TIME < 1500+TIMEOFFSET THEN 
   BEGIN
      IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.010000*VALUE11 THEN Buy to Cover ("SX3") NEXT BAR ENTRY ("S1") ENTRYPRICE-1 STOP ;
      IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.010000*VALUE11 THEN Sell ("LX3") NEXT BAR ENTRY ("L1") ENTRYPRICE+1 STOP ;
      IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.010000*VALUE11 THEN Buy to Cover ("SX32") NEXT BAR ENTRY ("S2") ENTRYPRICE-1 STOP ;
      IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.010000*VALUE11 THEN Sell ("LX32") NEXT BAR ENTRY ("L2") ENTRYPRICE+1 STOP ;
   END ;
   
   IF TIME >= 930+TIMEOFFSET AND TIME <= 1500+TIMEOFFSET THEN 
   BEGIN
      IF SPECTREND = 1 THEN 
      BEGIN
         IF SCENTRIES = 1 AND SPECLENTRIES = 0 AND SPECSENTRIES = 0 AND ENTRYPRICE (1)-EXITPRICE (1) < 2 AND TIME <= 1300+TIMEOFFSET THEN 
         BEGIN
            Buy ("L3") NEXT BAR MAXLIST (VALUE2, VALUE4)+0.050000 STOP ;
            IF HIGH > MAXLIST (VALUE11, VALUE2, VALUE4)+0.050000 THEN SPECLENTRIES = 1 ;
         END ;
         
         IF LCENTRIES = 1 AND SPECSENTRIES = 0 AND SPECLENTRIES = 0 AND EXITPRICE (1)-ENTRYPRICE (1) < 2 AND TIME <= 1300+TIMEOFFSET THEN 
         BEGIN
            Sell Short ("S3") NEXT BAR MINLIST (VALUE3, VALUE5)-0.050000 STOP ;
            IF LOW < MINLIST (VALUE3, VALUE5)-0.050000 THEN SPECSENTRIES = 1 ;
         END ;
         
         Sell ("LX4") NEXT BAR ENTRY ("L3") AT LOW DATA (2)-0.700000 STOP ;
         Buy to Cover ("SX4") NEXT BAR ENTRY ("S3") AT HIGH DATA (2)+0.700000 STOP ;
         IF MARKETPOSITION > 0 THEN Sell ("LX5") NEXT BAR ENTRY ("L3") MAXLIST (VALUE2, VALUE4)+0.050000+0.015000*VALUE11 LIMIT ;
         IF MARKETPOSITION < 0 THEN Buy to Cover ("LX6") NEXT BAR ENTRY ("S3") MINLIST (VALUE3, VALUE5)-0.050000-0.015000*VALUE11 LIMIT ;
         IF MARKETPOSITION > 0 THEN Sell ("SX5") NEXT BAR ENTRY ("L3") MAXLIST (VALUE2, VALUE4)+0.050000-(0.010000*VALUE11) STOP ;
         IF MARKETPOSITION < 0 THEN Buy to Cover ("SX6") NEXT BAR ENTRY ("S3") MINLIST (VALUE3, VALUE5)-0.050000+(0.010000*VALUE11) STOP ;
         IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.009000*VALUE11 THEN Buy to Cover ("SX7") NEXT BAR ENTRY ("S3") ENTRYPRICE-1 STOP ;
         IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.009000*VALUE11 THEN Sell ("LX7") NEXT BAR ENTRY ("L3") ENTRYPRICE+1 STOP ;
      END ;
      
   END ;
   
   IF TIME = SESS1ENDTIME THEN Buy ("L4") NEXT BAR 0.982000*CLOSE LIMIT ;
   IF TIME = SESS1ENDTIME THEN Sell Short ("S4") NEXT BAR 1.018000*CLOSE LIMIT ;
   IF TIME < 850+TIMEOFFSET THEN 
   BEGIN
      IF LCENTRIES < 1 AND LENTRIES < 1 THEN Buy ("L42") NEXT BAR 0.982000*VALUE11 LIMIT ;
      IF SCENTRIES < 1 THEN Sell Short ("S42") NEXT BAR 1.018000*VALUE11 LIMIT ;
   END ;
   
   IF TIME < 900+TIMEOFFSET AND MARKETPOSITION <> 0 THEN 
   BEGIN
      SPECTREND = 1 ;
   END ;
   
   IF MARKETPOSITION < 0 THEN 
   BEGIN
      SCENTRIES = 1 ;
      Buy to Cover ("SX8") NEXT BAR ENTRY ("S4") ENTRYPRICE+(0.012000*VALUE11) STOP ;
      Buy to Cover ("SX82") NEXT BAR ENTRY ("S42") ENTRYPRICE+(0.012000*VALUE11) STOP ;
   END ;
   
   IF MARKETPOSITION > 0 THEN 
   BEGIN
      LCENTRIES = 1 ;
      Sell ("LX8") NEXT BAR ENTRY ("L4") ENTRYPRICE-(0.012000*VALUE11) STOP ;
      Sell ("LX82") NEXT BAR ENTRY ("L42") ENTRYPRICE-(0.012000*VALUE11) STOP ;
   END ;
   
   IF TIME >= 900+TIMEOFFSET AND TIME <= 930+TIMEOFFSET THEN 
   BEGIN
      IF MARKETPOSITION > 0 THEN Sell ("L4Exit") NEXT BAR ENTRY ("L4") VALUE3-0.700000 STOP ;
      IF MARKETPOSITION > 0 THEN Sell ("L4Exit2") NEXT BAR ENTRY ("L42") VALUE3-0.700000 STOP ;
      IF MARKETPOSITION < 0 THEN Buy to Cover ("S4Exit") NEXT BAR ENTRY ("S4") VALUE2+0.700000 STOP ;
      IF MARKETPOSITION < 0 THEN Buy to Cover ("S4Exit2") NEXT BAR ENTRY ("S42") VALUE2+0.700000 STOP ;
   END ;
   
   IF TIME >= 930+TIMEOFFSET AND TIME < 1500+TIMEOFFSET THEN 
   BEGIN
      IF MARKETPOSITION > 0 THEN Sell ("L4Exit3") NEXT BAR ENTRY ("L4") Lowest (LOW DATA (2), 2)-0.700000 STOP ;
      IF MARKETPOSITION > 0 THEN Sell ("L4Exit4") NEXT BAR ENTRY ("L42") Lowest (LOW DATA (2), 2)-0.700000 STOP ;
      IF MARKETPOSITION < 0 THEN Buy to Cover ("SX9") NEXT BAR ENTRY ("S4") Highest (HIGH DATA (2), 2)+0.700000 STOP ;
      IF MARKETPOSITION < 0 THEN Buy to Cover ("SX10") NEXT BAR ENTRY ("S42") Highest (HIGH DATA (2), 2)+0.700000 STOP ;
      IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.007500*VALUE11 THEN Buy to Cover ("SX11") NEXT BAR ENTRY ("S4") ENTRYPRICE-1 STOP ;
      IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.007500*VALUE11 THEN Buy to Cover ("SX112") NEXT BAR ENTRY ("S42") ENTRYPRICE-1 STOP ;
      IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.007500*VALUE11 THEN Sell ("LX11") NEXT BAR ENTRY ("L4") ENTRYPRICE+1 STOP ;
      IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= 0.007500*VALUE11 THEN Sell ("LX112") NEXT BAR ENTRY ("L42") ENTRYPRICE+1 STOP ;
   END ;
   
   IF TIME >= 1500+TIMEOFFSET AND TIME <= 1514+TIMEOFFSET THEN 
   BEGIN
      Sell ("LX13") NEXT BAR LOW DATA (1)-0.050000 STOP ;
      Buy to Cover ("SX13") NEXT BAR HIGH DATA (1)+0.050000 STOP ;
   END ;
   
   IF (TIME <= 900+TIMEOFFSET AND MARKETPOSITION = 0) THEN STENTRIESB = 1 ;
   IF (TIME <= 900+TIMEOFFSET AND MARKETPOSITION <> 0) THEN STENTRIESB = 0 ;
   IF STENTRIESB = 1 AND (TIME >= 930+TIMEOFFSET AND MARKETPOSITION < 0) THEN LTRENDREV = 1 ;
   IF TIME < 1400+TIMEOFFSET AND LTRENDREV = 1 AND LTRENTRIES = 0 AND STRENTRIES = 0 THEN Buy ("L5") NEXT BAR IDHigh+0.050000 STOP ;
   IF LTRENDREV = 1 AND MARKETPOSITION > 0 THEN LTRENTRIES = 1 ;
   IF TIME <= 900+TIMEOFFSET AND MARKETPOSITION = 0 THEN LTENTRIESB = 1 ;
   IF TIME <= 900+TIMEOFFSET AND MARKETPOSITION <> 0 THEN LTENTRIESB = 0 ;
   IF LTENTRIESB = 1 AND (TIME >= 930+TIMEOFFSET AND MARKETPOSITION > 0) THEN STRENDREV = 1 ;
   IF TIME < 1400+TIMEOFFSET AND STRENDREV = 1 AND STRENTRIES = 0 AND LTRENTRIES = 0 THEN Sell Short ("S5") NEXT BAR IDLow-0.050000 STOP ;
   IF STRENDREV = 1 AND MARKETPOSITION < 0 THEN STRENTRIES = 1 ;
   IF MARKETPOSITION > 0 THEN Sell ("LX14") NEXT BAR ENTRY ("L5") ENTRYPRICE+(0.017500)*VALUE11 LIMIT ;
   IF MARKETPOSITION < 0 THEN Buy to Cover ("SX14") NEXT BAR ENTRY ("S5") ENTRYPRICE-(0.017500)*VALUE11 LIMIT ;
   IF MARKETPOSITION < 0 THEN Buy to Cover ("SX15") NEXT BAR ENTRY ("S5") ENTRYPRICE+(0.012000*VALUE11) STOP ;
   IF MARKETPOSITION > 0 THEN Sell ("LX15") NEXT BAR ENTRY ("L5") ENTRYPRICE-(0.012000*VALUE11) STOP ;
   IF TIME >= 930+TIMEOFFSET AND TIME < 1515+TIMEOFFSET THEN 
   BEGIN
      IF MARKETPOSITION < 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= (0.005000)*VALUE11 THEN Buy to Cover ("SX16") NEXT BAR ENTRY ("S5") ENTRYPRICE-3 STOP ;
      IF MARKETPOSITION > 0 AND MAXPOSITIONPROFIT/(POINTVALUE*PRICESCALE) >= (0.005000)*VALUE11 THEN Sell ("LX16") NEXT BAR ENTRY ("L5") ENTRYPRICE+3 STOP ;
   END ;
   
   IF TIME >= 1430+TIMEOFFSET AND TIME <= 1515+TIMEOFFSET THEN 
   BEGIN
      IF MARKETPOSITION > 0 THEN Sell ("LX17") NEXT BAR ENTRY ("L5") LOW DATA (1)-0.050000 STOP ;
      IF MARKETPOSITION < 0 THEN Buy to Cover ("SX17") NEXT BAR ENTRY ("S5") HIGH DATA (1)+0.050000 STOP ;
   END ;
   
   IF MARKETPOSITION <> 0 THEN TODAYTRADES = TODAYTRADES+1 ;
   //IncludeSystem:"Close at End of Day";

